### ISSUE TITLE
Multikit-assigning scripts not deleted upon uninstalling

### ISSUE THREAD

**Issue by CrevsDaak** [CrevsDaak/m7multikit#15]
Title says all. Minor. Will probably fix for 0.27.10.

**Comment by Darth-Cthoras** [comment]
Using MultKit v28 on a Windows 10 machine, BG2 EE, even after creating *and* installing a custom multikit that I confirmed shows up in character creation, the assigning scripts are apparently not being built at all. There's no new scripts viewable in-game in Records, and checking the Scripts folder, no new scripts have been made in weeks since I installed the game initially.
