### ISSUE TITLE
[v28] Incorrect directory pathing with BWS / BWP / EE Setup

### ISSUE THREAD

**Issue by Darth-Cthoras** [CrevsDaak/m7multikit#19]
PREFIX: Using these, the megamod managers for Baldur's Gate EE series (and possibly original series?) are extracting all files and folders within the archive's CrevsDaak-m7multikit-XXXXXXX folder directly into \Baldur's Gate II - Enhanced Edition, which is breaking the mod install for those managers, since the structure becomes 

\Baldur's Gate II - Enhanced Edition\languages
\Baldur's Gate II - Enhanced Edition\lib
\Baldur's Gate II - Enhanced Edition\multikit
\Baldur's Gate II - Enhanced Edition\TobEx_redist

PROBLEM: Specifically that when installed from BG2's folder in such a way, Weidu is grabbing the Dialog.tlk instead of MultiKit's English.Tra, causing translation errors to fail the install.

Solution: Once I made the folder \Baldur's Gate II - Enhanced Edition\m7multikit\languages, with English.Tra in that folder, the install worked perfectly.

**Comment by CrevsDaak** [comment]
Having everything within a second m7multikit directory makes it really annoying for me to work on the mod, and I'm not exactly willing to change it. What I'd suggest is you either extract the mod separately before running BWS or install it manually after you're done with BWS (I would recommend this, since this mod in particular benefits from being installed last—because you can uninstall it more easily after it rather expectedly fails as often as it does).

**Comment by Darth-Cthoras** [comment]
That's fine. No one would expect you to support two identical folders of files. I just wanted it documented for future users and myself if I ever forget.
